[package]
name = "curiosities-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
scraper = "0.18.1"
